//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com. 
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(TermsAndAcronymsPage.CLASS_NAME, typeof(TermsAndAcronymsPage))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Sample item class.
    /// </summary>
    public partial class TermsAndAcronymsPage : TreeNode
    {
        #region "Constants"

        /// <summary>
        /// Class name of the item.
        /// </summary>
        public const string CLASS_NAME = "custom.TermsAndAcronymsPage";

        #endregion


        #region "Properties"

        /// <summary>
        /// TermsAndAcronimsPageID.
        /// </summary>
        [DatabaseField]
        public int TermsAndAcronimsPageID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TermsAndAcronimsPageID"), 0);
            }
            set
            {
                SetValue("TermsAndAcronimsPageID", value);
            }
        }


        /// <summary>
        /// Tile Title.
        /// </summary>
        [DatabaseField]
        public string TileTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TileTitle"), "");
            }
            set
            {
                SetValue("TileTitle", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), "");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Image displayed on a tile.
        /// </summary>
        [DatabaseField]
        public string HomeImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomeImage"), "");
            }
            set
            {
                SetValue("HomeImage", value);
            }
        }


        /// <summary>
        /// Text that appears on hover over the tile.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Description"), "");
            }
            set
            {
                SetValue("Description", value);
            }
        }


        /// <summary>
        /// Search Label.
        /// </summary>
        [DatabaseField]
        public string SearchLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SearchLabel"), "");
            }
            set
            {
                SetValue("SearchLabel", value);
            }
        }


        /// <summary>
        /// Sort Label.
        /// </summary>
        [DatabaseField]
        public string SortLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SortLabel"), "");
            }
            set
            {
                SetValue("SortLabel", value);
            }
        }


        /// <summary>
        /// First Char In Alphabet Label.
        /// </summary>
        [DatabaseField]
        public string FirstCharInAlphabetLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FirstCharInAlphabetLabel"), "");
            }
            set
            {
                SetValue("FirstCharInAlphabetLabel", value);
            }
        }


        /// <summary>
        /// Last Char In Alphabet Label.
        /// </summary>
        [DatabaseField]
        public string LastCharInAlphabetLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LastCharInAlphabetLabel"), "");
            }
            set
            {
                SetValue("LastCharInAlphabetLabel", value);
            }
        }


        /// <summary>
        /// Loading Label.
        /// </summary>
        [DatabaseField]
        public string LoadingLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LoadingLabel"), "");
            }
            set
            {
                SetValue("LoadingLabel", value);
            }
        }


        /// <summary>
        /// No Items Label.
        /// </summary>
        [DatabaseField]
        public string NoItemsLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("NoItemsLabel"), "");
            }
            set
            {
                SetValue("NoItemsLabel", value);
            }
        }


        /// <summary>
        /// Sidebar Items.
        /// </summary>
        [DatabaseField]
        public string SidebarItems
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SidebarItems"), "");
            }
            set
            {
                SetValue("SidebarItems", value);
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Constructor.
        /// </summary>
        public TermsAndAcronymsPage()
            : base(CLASS_NAME)
        {
        }

        #endregion
    }
}
