//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com. 
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(GlobalSearchPage.CLASS_NAME, typeof(GlobalSearchPage))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Sample item class.
    /// </summary>
    public partial class GlobalSearchPage : TreeNode
    {
        #region "Constants"

        /// <summary>
        /// Class name of the item.
        /// </summary>
        public const string CLASS_NAME = "custom.GlobalSearchPage";

        #endregion


        #region "Properties"

        /// <summary>
        /// GlobalSearchPageID.
        /// </summary>
        [DatabaseField]
        public int GlobalSearchPageID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("GlobalSearchPageID"), 0);
            }
            set
            {
                SetValue("GlobalSearchPageID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), "");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Results For Label.
        /// </summary>
        [DatabaseField]
        public string ResultsForLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ResultsForLabel"), "");
            }
            set
            {
                SetValue("ResultsForLabel", value);
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Constructor.
        /// </summary>
        public GlobalSearchPage()
            : base(CLASS_NAME)
        {
        }

        #endregion
    }
}
