//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com. 
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(GenericPage.CLASS_NAME, typeof(GenericPage))]

namespace CMS.DocumentEngine.Types
{
	/// <summary>
	/// Sample item class.
	/// </summary>
	public partial class GenericPage : TreeNode
	{
		#region "Constants"

		/// <summary>
		/// Class name of the item.
		/// </summary>
		public const string CLASS_NAME = "custom.GenericPage";

		#endregion


		#region "Properties"

		/// <summary>
		/// GenericPageID.
		/// </summary>
		[DatabaseField]
		public int GenericPageID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("GenericPageID"), 0);
			}
			set
			{
				SetValue("GenericPageID", value);
			}
		}


		/// <summary>
		/// 
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), "");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Copy.
		/// </summary>
		[DatabaseField]
		public string Copy
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Copy"), "");
			}
			set
			{
				SetValue("Copy", value);
			}
		}


		/// <summary>
		/// 
		/// </summary>
		[DatabaseField]
		public DateTime PostedDate
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("PostedDate"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("PostedDate", value);
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Constructor.
		/// </summary>
		public GenericPage()
			: base(CLASS_NAME)
		{
		}

		#endregion
	}
}
