//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com. 
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(RateContent.CLASS_NAME, typeof(RateContent))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Sample item class.
    /// </summary>
    public partial class RateContent : TreeNode
    {
        #region "Constants"

        /// <summary>
        /// Class name of the item.
        /// </summary>
        public const string CLASS_NAME = "custom.RateContent";

        #endregion


        #region "Properties"

        /// <summary>
        /// RateContentID.
        /// </summary>
        [DatabaseField]
        public int RateContentID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("RateContentID"), 0);
            }
            set
            {
                SetValue("RateContentID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), "");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Rated Document.
        /// </summary>
        [DatabaseField]
        public Guid RatedDocument
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("RatedDocument"), Guid.Empty);
            }
            set
            {
                SetValue("RatedDocument", value);
            }
        }


        /// <summary>
        /// Rated Contact.
        /// </summary>
        [DatabaseField]
        public Guid RatedContact
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("RatedContact"), Guid.Empty);
            }
            set
            {
                SetValue("RatedContact", value);
            }
        }


        /// <summary>
        /// Is Helpful.
        /// </summary>
        [DatabaseField]
        public bool IsHelpful
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("IsHelpful"), false);
            }
            set
            {
                SetValue("IsHelpful", value);
            }
        }


        /// <summary>
        /// Message.
        /// </summary>
        [DatabaseField]
        public string Message
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Message"), "");
            }
            set
            {
                SetValue("Message", value);
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Constructor.
        /// </summary>
        public RateContent()
            : base(CLASS_NAME)
        {
        }

        #endregion
    }
}
