//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(LogisticsAndSupplyFolder.CLASS_NAME, typeof(LogisticsAndSupplyFolder))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Represents a content item of type LogisticsAndSupplyFolder.
    /// </summary>
    public partial class LogisticsAndSupplyFolder : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "custom.LogisticsAndSupplyFolder";


        /// <summary>
        /// The instance of the class that provides extended API for working with LogisticsAndSupplyFolder fields.
        /// </summary>
        private readonly LogisticsAndSupplyFolderFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// LogisticsAndSupplyFolderID.
        /// </summary>
        [DatabaseIDField]
        public int LogisticsAndSupplyFolderID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("LogisticsAndSupplyFolderID"), 0);
            }
            set
            {
                SetValue("LogisticsAndSupplyFolderID", value);
            }
        }


        /// <summary>
        /// Tile Title.
        /// </summary>
        [DatabaseField]
        public string TileTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TileTitle"), "");
            }
            set
            {
                SetValue("TileTitle", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), "");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Text that appears on hover over the tile.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Description"), "");
            }
            set
            {
                SetValue("Description", value);
            }
        }


        /// <summary>
        /// Image displayed on a tile.
        /// </summary>
        [DatabaseField]
        public string HomeImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomeImage"), "");
            }
            set
            {
                SetValue("HomeImage", value);
            }
        }


        /// <summary>
        /// Abstract.
        /// </summary>
        [DatabaseField]
        public string Abstract
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Abstract"), "");
            }
            set
            {
                SetValue("Abstract", value);
            }
        }


        /// <summary>
        /// Copy.
        /// </summary>
        [DatabaseField]
        public string Copy
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Copy"), "");
            }
            set
            {
                SetValue("Copy", value);
            }
        }


        /// <summary>
        /// Hero Image.
        /// </summary>
        [DatabaseField]
        public string HeroImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HeroImage"), "");
            }
            set
            {
                SetValue("HeroImage", value);
            }
        }


        /// <summary>
        /// Sidebar Items.
        /// </summary>
        [DatabaseField]
        public string SidebarItems
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SidebarItems"), "");
            }
            set
            {
                SetValue("SidebarItems", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with LogisticsAndSupplyFolder fields.
        /// </summary>
        public LogisticsAndSupplyFolderFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with LogisticsAndSupplyFolder fields.
        /// </summary>
        public partial class LogisticsAndSupplyFolderFields
        {
            /// <summary>
            /// The content item of type LogisticsAndSupplyFolder that is a target of the extended API.
            /// </summary>
            private readonly LogisticsAndSupplyFolder mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="LogisticsAndSupplyFolderFields" /> class with the specified content item of type LogisticsAndSupplyFolder.
            /// </summary>
            /// <param name="instance">The content item of type LogisticsAndSupplyFolder that is a target of the extended API.</param>
            public LogisticsAndSupplyFolderFields(LogisticsAndSupplyFolder instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// LogisticsAndSupplyFolderID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.LogisticsAndSupplyFolderID;
                }
                set
                {
                    mInstance.LogisticsAndSupplyFolderID = value;
                }
            }


            /// <summary>
            /// Tile Title.
            /// </summary>
            public string TileTitle
            {
                get
                {
                    return mInstance.TileTitle;
                }
                set
                {
                    mInstance.TileTitle = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Text that appears on hover over the tile.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.Description;
                }
                set
                {
                    mInstance.Description = value;
                }
            }


            /// <summary>
            /// Image displayed on a tile.
            /// </summary>
            public string HomeImage
            {
                get
                {
                    return mInstance.HomeImage;
                }
                set
                {
                    mInstance.HomeImage = value;
                }
            }


            /// <summary>
            /// Abstract.
            /// </summary>
            public string Abstract
            {
                get
                {
                    return mInstance.Abstract;
                }
                set
                {
                    mInstance.Abstract = value;
                }
            }


            /// <summary>
            /// Copy.
            /// </summary>
            public string Copy
            {
                get
                {
                    return mInstance.Copy;
                }
                set
                {
                    mInstance.Copy = value;
                }
            }


            /// <summary>
            /// Hero Image.
            /// </summary>
            public string HeroImage
            {
                get
                {
                    return mInstance.HeroImage;
                }
                set
                {
                    mInstance.HeroImage = value;
                }
            }


            /// <summary>
            /// Sidebar Items.
            /// </summary>
            public IEnumerable<TreeNode> SidebarItems2
            {
                get
                {
                    return mInstance.GetRelatedDocuments("SidebarItems2");
                }
            }


            /// <summary>
            /// Sidebar Items.
            /// </summary>
            public string SidebarItems
            {
                get
                {
                    return mInstance.SidebarItems;
                }
                set
                {
                    mInstance.SidebarItems = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="LogisticsAndSupplyFolder" /> class.
        /// </summary>
        public LogisticsAndSupplyFolder()
            : base(CLASS_NAME)
        {
            mFields = new LogisticsAndSupplyFolderFields(this);
        }

        #endregion
    }
}