//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com. 
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(SolutionConstants.CLASS_NAME, typeof(SolutionConstants))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Sample item class.
    /// </summary>
    public partial class SolutionConstants : TreeNode
    {
        #region "Constants"

        /// <summary>
        /// Class name of the item.
        /// </summary>
        public const string CLASS_NAME = "custom.SolutionConstants";

        #endregion


        #region "Properties"

        /// <summary>
        /// SolutionConstantsID.
        /// </summary>
        [DatabaseField]
        public int SolutionConstantsID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("SolutionConstantsID"), 0);
            }
            set
            {
                SetValue("SolutionConstantsID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), "");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// View All Label.
        /// </summary>
        [DatabaseField]
        public string ViewAllLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ViewAllLabel"), "");
            }
            set
            {
                SetValue("ViewAllLabel", value);
            }
        }


        /// <summary>
        /// Products Label.
        /// </summary>
        [DatabaseField]
        public string ProductsLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ProductsLabel"), "");
            }
            set
            {
                SetValue("ProductsLabel", value);
            }
        }


        /// <summary>
        /// Product Card Type (Driveline Additives).
        /// </summary>
        [DatabaseField]
        public string ProductCardType
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ProductCardType"), "");
            }
            set
            {
                SetValue("ProductCardType", value);
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Constructor.
        /// </summary>
        public SolutionConstants()
            : base(CLASS_NAME)
        {
        }

        #endregion
    }
}

