//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Solution.CLASS_NAME, typeof(Solution))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Represents a content item of type Solution.
    /// </summary>
    public partial class Solution : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "custom.Solution";


        /// <summary>
        /// The instance of the class that provides extended API for working with Solution fields.
        /// </summary>
        private readonly SolutionFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// SolutionID.
        /// </summary>
        [DatabaseIDField]
        public int SolutionID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("SolutionID"), 0);
            }
            set
            {
                SetValue("SolutionID", value);
            }
        }


        /// <summary>
        /// Tile Title.
        /// </summary>
        [DatabaseField]
        public string TileTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TileTitle"), "");
            }
            set
            {
                SetValue("TileTitle", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), "");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Image displayed on a tile.
        /// </summary>
        [DatabaseField]
        public string HomeImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomeImage"), "");
            }
            set
            {
                SetValue("HomeImage", value);
            }
        }


        /// <summary>
        /// Text that appears on hover over the tile.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Description"), "");
            }
            set
            {
                SetValue("Description", value);
            }
        }


        /// <summary>
        /// Subtitle.
        /// </summary>
        [DatabaseField]
        public string Subtitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Subtitle"), "");
            }
            set
            {
                SetValue("Subtitle", value);
            }
        }


        /// <summary>
        /// Hero Image.
        /// </summary>
        [DatabaseField]
        public string HeroImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HeroImage"), "");
            }
            set
            {
                SetValue("HeroImage", value);
            }
        }


        /// <summary>
        /// Copy.
        /// </summary>
        [DatabaseField]
        public string Copy
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Copy"), "");
            }
            set
            {
                SetValue("Copy", value);
            }
        }


        /// <summary>
        /// Navigation Icon.
        /// </summary>
        [DatabaseField]
        public string NavigationIcon
        {
            get
            {
                return ValidationHelper.GetString(GetValue("NavigationIcon"), "");
            }
            set
            {
                SetValue("NavigationIcon", value);
            }
        }


        /// <summary>
        /// Featured Product List.
        /// </summary>
        [DatabaseField]
        public string FeaturedProductList
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FeaturedProductList"), "");
            }
            set
            {
                SetValue("FeaturedProductList", value);
            }
        }


        /// <summary>
        /// Sidebar Items.
        /// </summary>
        [DatabaseField]
        public string SidebarItems
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SidebarItems"), "");
            }
            set
            {
                SetValue("SidebarItems", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string SidebarTest
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SidebarTest"), "");
            }
            set
            {
                SetValue("SidebarTest", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with Solution fields.
        /// </summary>
        public SolutionFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with Solution fields.
        /// </summary>
        public partial class SolutionFields
        {
            /// <summary>
            /// The content item of type Solution that is a target of the extended API.
            /// </summary>
            private readonly Solution mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="SolutionFields" /> class with the specified content item of type Solution.
            /// </summary>
            /// <param name="instance">The content item of type Solution that is a target of the extended API.</param>
            public SolutionFields(Solution instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// SolutionID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.SolutionID;
                }
                set
                {
                    mInstance.SolutionID = value;
                }
            }


            /// <summary>
            /// Tile Title.
            /// </summary>
            public string TileTitle
            {
                get
                {
                    return mInstance.TileTitle;
                }
                set
                {
                    mInstance.TileTitle = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Image displayed on a tile.
            /// </summary>
            public string HomeImage
            {
                get
                {
                    return mInstance.HomeImage;
                }
                set
                {
                    mInstance.HomeImage = value;
                }
            }


            /// <summary>
            /// Text that appears on hover over the tile.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.Description;
                }
                set
                {
                    mInstance.Description = value;
                }
            }


            /// <summary>
            /// Subtitle.
            /// </summary>
            public string Subtitle
            {
                get
                {
                    return mInstance.Subtitle;
                }
                set
                {
                    mInstance.Subtitle = value;
                }
            }


            /// <summary>
            /// Hero Image.
            /// </summary>
            public string HeroImage
            {
                get
                {
                    return mInstance.HeroImage;
                }
                set
                {
                    mInstance.HeroImage = value;
                }
            }


            /// <summary>
            /// Copy.
            /// </summary>
            public string Copy
            {
                get
                {
                    return mInstance.Copy;
                }
                set
                {
                    mInstance.Copy = value;
                }
            }


            /// <summary>
            /// Navigation Icon.
            /// </summary>
            public string NavigationIcon
            {
                get
                {
                    return mInstance.NavigationIcon;
                }
                set
                {
                    mInstance.NavigationIcon = value;
                }
            }


            /// <summary>
            /// Featured Product List.
            /// </summary>
            public string FeaturedProductList
            {
                get
                {
                    return mInstance.FeaturedProductList;
                }
                set
                {
                    mInstance.FeaturedProductList = value;
                }
            }


            /// <summary>
            /// Sidebar Items.
            /// </summary>
            public string SidebarItems
            {
                get
                {
                    return mInstance.SidebarItems;
                }
                set
                {
                    mInstance.SidebarItems = value;
                }
            }


            /// <summary>
            /// Sidebar Items.
            /// </summary>
            public IEnumerable<TreeNode> SidebarItems2
            {
                get
                {
                    return mInstance.GetRelatedDocuments("SidebarItems2");
                }
            }


            /// <summary>
            /// 
            /// </summary>
            public string SidebarTest
            {
                get
                {
                    return mInstance.SidebarTest;
                }
                set
                {
                    mInstance.SidebarTest = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="Solution" /> class.
        /// </summary>
        public Solution()
            : base(CLASS_NAME)
        {
            mFields = new SolutionFields(this);
        }

        #endregion
    }
}