//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com. 
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(BlogPost.CLASS_NAME, typeof(BlogPost))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Sample item class.
    /// </summary>
    public partial class BlogPost : TreeNode
    {
        #region "Constants"

        /// <summary>
        /// Class name of the item.
        /// </summary>
        public const string CLASS_NAME = "CMS.BlogPost";

        #endregion


        #region "Properties"

        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public int BlogPostID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("BlogPostID"), 0);
            }
            set
            {
                SetValue("BlogPostID", value);
            }
        }


        /// <summary>
        /// Post title.
        /// </summary>
        [DatabaseField]
        public string BlogPostTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BlogPostTitle"), "");
            }
            set
            {
                SetValue("BlogPostTitle", value);
            }
        }


        /// <summary>
        /// Post date.
        /// </summary>
        [DatabaseField]
        public DateTime BlogPostDate
        {
            get
            {
                return ValidationHelper.GetDateTime(GetValue("BlogPostDate"), ValidationHelper.GetDateTime("##TODAY##", DateTimeHelper.ZERO_TIME));
            }
            set
            {
                SetValue("BlogPostDate", value);
            }
        }


        /// <summary>
        /// Post summary.
        /// </summary>
        [DatabaseField]
        public string BlogPostSummary
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BlogPostSummary"), "");
            }
            set
            {
                SetValue("BlogPostSummary", value);
            }
        }


        /// <summary>
        /// Post text.
        /// </summary>
        [DatabaseField]
        public string BlogPostBody
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BlogPostBody"), "");
            }
            set
            {
                SetValue("BlogPostBody", value);
            }
        }


        /// <summary>
        /// Post teaser.
        /// </summary>
        [DatabaseField]
        public Guid BlogPostTeaser
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("BlogPostTeaser"), Guid.Empty);
            }
            set
            {
                SetValue("BlogPostTeaser", value);
            }
        }


        /// <summary>
        /// Allow comments.
        /// </summary>
        [DatabaseField]
        public bool BlogPostAllowComments
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("BlogPostAllowComments"), true);
            }
            set
            {
                SetValue("BlogPostAllowComments", value);
            }
        }


        /// <summary>
        /// Already pinged.
        /// </summary>
        [DatabaseField]
        public string BlogPostPingedUrls
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BlogPostPingedUrls"), "");
            }
            set
            {
                SetValue("BlogPostPingedUrls", value);
            }
        }


        /// <summary>
        /// Send trackbacks to.
        /// </summary>
        [DatabaseField]
        public string BlogPostNotPingedUrls
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BlogPostNotPingedUrls"), "");
            }
            set
            {
                SetValue("BlogPostNotPingedUrls", value);
            }
        }


        /// <summary>
        /// Log on-line marketing activity.
        /// </summary>
        [DatabaseField]
        public bool BlogLogActivity
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("BlogLogActivity"), true);
            }
            set
            {
                SetValue("BlogLogActivity", value);
            }
        }


        /// <summary>
        /// Post to Facebook.
        /// </summary>
        [DatabaseField]
        public string FacebookAutoPost
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FacebookAutoPost"), "");
            }
            set
            {
                SetValue("FacebookAutoPost", value);
            }
        }


        /// <summary>
        /// Post to Twitter.
        /// </summary>
        [DatabaseField]
        public string TwitterAutoPost
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TwitterAutoPost"), "");
            }
            set
            {
                SetValue("TwitterAutoPost", value);
            }
        }


        /// <summary>
        /// Post to LinkedIn.
        /// </summary>
        [DatabaseField]
        public string LinkedInAutoPost
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LinkedInAutoPost"), "");
            }
            set
            {
                SetValue("LinkedInAutoPost", value);
            }
        }


        /// <summary>
        /// Sidebar Items.
        /// </summary>
        [DatabaseField]
        public string SidebarItems
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SidebarItems"), "");
            }
            set
            {
                SetValue("SidebarItems", value);
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Constructor.
        /// </summary>
        public BlogPost()
            : base(CLASS_NAME)
        {
        }

        #endregion
    }
}
