//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com. 
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(BlogsPage.CLASS_NAME, typeof(BlogsPage))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Sample item class.
    /// </summary>
    public partial class BlogsPage : TreeNode
    {
        #region "Constants"

        /// <summary>
        /// Class name of the item.
        /// </summary>
        public const string CLASS_NAME = "custom.BlogsPage";

        #endregion


        #region "Properties"

        /// <summary>
        /// BlogsPageID.
        /// </summary>
        [DatabaseField]
        public int BlogsPageID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("BlogsPageID"), 0);
            }
            set
            {
                SetValue("BlogsPageID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), "");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Description"), "");
            }
            set
            {
                SetValue("Description", value);
            }
        }


        /// <summary>
        /// Content Managed Tiles.
        /// </summary>
        [DatabaseField]
        public string ContentManagedTiles
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ContentManagedTiles"), "");
            }
            set
            {
                SetValue("ContentManagedTiles", value);
            }
        }


        /// <summary>
        /// Read More Label.
        /// </summary>
        [DatabaseField]
        public string ReadMoreLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ReadMoreLabel"), "");
            }
            set
            {
                SetValue("ReadMoreLabel", value);
            }
        }


        /// <summary>
        /// Sort Newest Label.
        /// </summary>
        [DatabaseField]
        public string SortNewestLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SortNewestLabel"), "");
            }
            set
            {
                SetValue("SortNewestLabel", value);
            }
        }


        /// <summary>
        /// Sort Oldest Label.
        /// </summary>
        [DatabaseField]
        public string SortOldestLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SortOldestLabel"), "");
            }
            set
            {
                SetValue("SortOldestLabel", value);
            }
        }


        /// <summary>
        /// All Categories Select Option.
        /// </summary>
        [DatabaseField]
        public string AllCategoriesSelectOption
        {
            get
            {
                return ValidationHelper.GetString(GetValue("AllCategoriesSelectOption"), "");
            }
            set
            {
                SetValue("AllCategoriesSelectOption", value);
            }
        }


        /// <summary>
        /// All Authors Select Option.
        /// </summary>
        [DatabaseField]
        public string AllAuthorsSelectOption
        {
            get
            {
                return ValidationHelper.GetString(GetValue("AllAuthorsSelectOption"), "");
            }
            set
            {
                SetValue("AllAuthorsSelectOption", value);
            }
        }

        /// <summary>
        /// TilesLabel.
        /// </summary>
        [DatabaseField]
        public string TilesLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TilesLabel"), "");
            }
            set
            {
                SetValue("TilesLabel", value);
            }
        }


        /// <summary>
        /// ViewAllLabel.
        /// </summary>
        [DatabaseField]
        public string ViewAllLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ViewAllLabel"), "");
            }
            set
            {
                SetValue("ViewAllLabel", value);
            }
        }


        /// <summary>
        /// Posted Label.
        /// </summary>
        [DatabaseField]
        public string PostedLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PostedLabel"), "");
            }
            set
            {
                SetValue("PostedLabel", value);
            }
        }

        /// <summary>
        /// Filter By Label.
        /// </summary>
        [DatabaseField]
        public string FilterByLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FilterByLabel"), "");
            }
            set
            {
                SetValue("FilterByLabel", value);
            }
        }


        /// <summary>
        /// Sort By Label.
        /// </summary>
        [DatabaseField]
        public string SortByLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SortByLabel"), "");
            }
            set
            {
                SetValue("SortByLabel", value);
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Constructor.
        /// </summary>
        public BlogsPage()
            : base(CLASS_NAME)
        {
        }

        #endregion
    }
}
