//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class CMSModules_OnlineMarketing_Pages_Content_ABTesting_ABVariant_Edit {
    
    /// <summary>
    /// pnlDisabled control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlDisabled;
    
   
    /// <summary>
    /// editElem control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSModules_OnlineMarketing_Controls_UI_ABVariant_Edit editElem;
    protected global::CMSAdminControls_Basic_DisabledModuleInfo ucDisabledModule;
}
