//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com. 
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(GenericSidebarBlock.CLASS_NAME, typeof(GenericSidebarBlock))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Sample item class.
    /// </summary>
    public partial class GenericSidebarBlock : TreeNode
    {
        #region "Constants"

        /// <summary>
        /// Class name of the item.
        /// </summary>
        public const string CLASS_NAME = "custom.GenericSidebarBlock";

        #endregion


        #region "Properties"

        /// <summary>
        /// GenericSidebarBlockID.
        /// </summary>
        [DatabaseField]
        public int GenericSidebarBlockID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("GenericSidebarBlockID"), 0);
            }
            set
            {
                SetValue("GenericSidebarBlockID", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Description"), "");
            }
            set
            {
                SetValue("Description", value);
            }
        }

        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), "");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Default Image.
        /// </summary>
        [DatabaseField]
        public string DefaultImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DefaultImage"), "");
            }
            set
            {
                SetValue("DefaultImage", value);
            }
        }


        /// <summary>
        /// SidebarItem.
        /// </summary>
        [DatabaseField]
        public string SidebarItem
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SidebarItem"), "");
            }
            set
            {
                SetValue("SidebarItem", value);
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Constructor.
        /// </summary>
        public GenericSidebarBlock()
            : base(CLASS_NAME)
        {
        }

        #endregion
    }
}
