//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com. 
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(FAQTopic.CLASS_NAME, typeof(FAQTopic))]

namespace CMS.DocumentEngine.Types
{
	/// <summary>
	/// Sample item class.
	/// </summary>
	public partial class FAQTopic : TreeNode
	{
		#region "Constants"

		/// <summary>
		/// Class name of the item.
		/// </summary>
		public const string CLASS_NAME = "custom.FAQTopic";

		#endregion


		#region "Properties"

		/// <summary>
		/// FAQTopicID.
		/// </summary>
		[DatabaseField]
		public int FAQTopicID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("FAQTopicID"), 0);
			}
			set
			{
				SetValue("FAQTopicID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), "");
			}
			set
			{
				SetValue("Name", value);
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Constructor.
		/// </summary>
		public FAQTopic()
			: base(CLASS_NAME)
		{
		}

		#endregion
	}
}
