//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType( NewsAndEventsPage.CLASS_NAME, typeof( NewsAndEventsPage ) )]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Represents a content item of type NewsAndEventsPage.
    /// </summary>
    public partial class NewsAndEventsPage : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "custom.NewsAndEventsPage";


        /// <summary>
        /// The instance of the class that provides extended API for working with NewsAndEventsPage fields.
        /// </summary>
        private readonly NewsAndEventsPageFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// NewsAndEventsPageID.
        /// </summary>
        [DatabaseIDField]
        public int NewsAndEventsPageID
        {
            get
            {
                return ValidationHelper.GetInteger( GetValue( "NewsAndEventsPageID" ), 0 );
            }
            set
            {
                SetValue( "NewsAndEventsPageID", value );
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string HomeTitle
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "HomeTitle" ), "" );
            }
            set
            {
                SetValue( "HomeTitle", value );
            }
        }


        /// <summary>
        /// Tile Title.
        /// </summary>
        [DatabaseField]
        public string TileTitle
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "TileTitle" ), "" );
            }
            set
            {
                SetValue( "TileTitle", value );
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "Title" ), "" );
            }
            set
            {
                SetValue( "Title", value );
            }
        }


        /// <summary>
        /// Image displayed on a tile.
        /// </summary>
        [DatabaseField]
        public string HomeImage
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "HomeImage" ), "" );
            }
            set
            {
                SetValue( "HomeImage", value );
            }
        }


        /// <summary>
        /// Text that appears on hover over the tile.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "Description" ), "" );
            }
            set
            {
                SetValue( "Description", value );
            }
        }


        /// <summary>
        /// Filter By Label.
        /// </summary>
        [DatabaseField]
        public string FilterByLabel
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "FilterByLabel" ), "" );
            }
            set
            {
                SetValue( "FilterByLabel", value );
            }
        }


        /// <summary>
        /// Sort By Label.
        /// </summary>
        [DatabaseField]
        public string SortByLabel
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "SortByLabel" ), "" );
            }
            set
            {
                SetValue( "SortByLabel", value );
            }
        }


        /// <summary>
        /// Event List.
        /// </summary>
        [DatabaseField]
        public string NewsAndEvents
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "NewsAndEvents" ), "" );
            }
            set
            {
                SetValue( "NewsAndEvents", value );
            }
        }


        /// <summary>
        /// News List.
        /// </summary>
        [DatabaseField]
        public string NewsList
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "NewsList" ), "" );
            }
            set
            {
                SetValue( "NewsList", value );
            }
        }


        /// <summary>
        /// Content Managed Tiles.
        /// </summary>
        [DatabaseField]
        public string ContentManagedTiles
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "ContentManagedTiles" ), "" );
            }
            set
            {
                SetValue( "ContentManagedTiles", value );
            }
        }


        /// <summary>
        /// Sort Newest Label.
        /// </summary>
        [DatabaseField]
        public string SortNewestLabel
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "SortNewestLabel" ), "" );
            }
            set
            {
                SetValue( "SortNewestLabel", value );
            }
        }


        /// <summary>
        /// Sort Oldest Label.
        /// </summary>
        [DatabaseField]
        public string SortOldestLabel
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "SortOldestLabel" ), "" );
            }
            set
            {
                SetValue( "SortOldestLabel", value );
            }
        }


        /// <summary>
        /// Tiles Label.
        /// </summary>
        [DatabaseField]
        public string TilesLabel
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "TilesLabel" ), "" );
            }
            set
            {
                SetValue( "TilesLabel", value );
            }
        }


        /// <summary>
        /// View All Label.
        /// </summary>
        [DatabaseField]
        public string ViewAllLabel
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "ViewAllLabel" ), "" );
            }
            set
            {
                SetValue( "ViewAllLabel", value );
            }
        }


        /// <summary>
        /// Posted Label.
        /// </summary>
        [DatabaseField]
        public string PostedLabel
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "PostedLabel" ), "" );
            }
            set
            {
                SetValue( "PostedLabel", value );
            }
        }


        /// <summary>
        /// Read More Label.
        /// </summary>
        [DatabaseField]
        public string ReadMoreLabel
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "ReadMoreLabel" ), "" );
            }
            set
            {
                SetValue( "ReadMoreLabel", value );
            }
        }


        /// <summary>
        /// All News Events Selector Value.
        /// </summary>
        [DatabaseField]
        public string AllNewsEventsSelectorValue
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "AllNewsEventsSelectorValue" ), "" );
            }
            set
            {
                SetValue( "AllNewsEventsSelectorValue", value );
            }
        }


        /// <summary>
        /// News Selector Value.
        /// </summary>
        [DatabaseField]
        public string NewsSelectorValue
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "NewsSelectorValue" ), "" );
            }
            set
            {
                SetValue( "NewsSelectorValue", value );
            }
        }


        /// <summary>
        /// Events Selector Value.
        /// </summary>
        [DatabaseField]
        public string EventsSelectorValue
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "EventsSelectorValue" ), "" );
            }
            set
            {
                SetValue( "EventsSelectorValue", value );
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with NewsAndEventsPage fields.
        /// </summary>
        public NewsAndEventsPageFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with NewsAndEventsPage fields.
        /// </summary>
        public partial class NewsAndEventsPageFields
        {
            /// <summary>
            /// The content item of type NewsAndEventsPage that is a target of the extended API.
            /// </summary>
            private readonly NewsAndEventsPage mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="NewsAndEventsPageFields" /> class with the specified content item of type NewsAndEventsPage.
            /// </summary>
            /// <param name="instance">The content item of type NewsAndEventsPage that is a target of the extended API.</param>
            public NewsAndEventsPageFields( NewsAndEventsPage instance )
            {
                mInstance = instance;
            }


            /// <summary>
            /// NewsAndEventsPageID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.NewsAndEventsPageID;
                }
                set
                {
                    mInstance.NewsAndEventsPageID = value;
                }
            }


            /// <summary>
            /// 
            /// </summary>
            public string HomeTitle
            {
                get
                {
                    return mInstance.HomeTitle;
                }
                set
                {
                    mInstance.HomeTitle = value;
                }
            }


            /// <summary>
            /// Tile Title.
            /// </summary>
            public string TileTitle
            {
                get
                {
                    return mInstance.TileTitle;
                }
                set
                {
                    mInstance.TileTitle = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Image displayed on a tile.
            /// </summary>
            public string HomeImage
            {
                get
                {
                    return mInstance.HomeImage;
                }
                set
                {
                    mInstance.HomeImage = value;
                }
            }


            /// <summary>
            /// Text that appears on hover over the tile.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.Description;
                }
                set
                {
                    mInstance.Description = value;
                }
            }


            /// <summary>
            /// Filter By Label.
            /// </summary>
            public string FilterByLabel
            {
                get
                {
                    return mInstance.FilterByLabel;
                }
                set
                {
                    mInstance.FilterByLabel = value;
                }
            }


            /// <summary>
            /// Sort By Label.
            /// </summary>
            public string SortByLabel
            {
                get
                {
                    return mInstance.SortByLabel;
                }
                set
                {
                    mInstance.SortByLabel = value;
                }
            }


            /// <summary>
            /// Event List.
            /// </summary>
            public string NewsAndEvents
            {
                get
                {
                    return mInstance.NewsAndEvents;
                }
                set
                {
                    mInstance.NewsAndEvents = value;
                }
            }


            /// <summary>
            /// News List.
            /// </summary>
            public string NewsList
            {
                get
                {
                    return mInstance.NewsList;
                }
                set
                {
                    mInstance.NewsList = value;
                }
            }


            /// <summary>
            /// Content Managed Tiles.
            /// </summary>
            public string ContentManagedTiles
            {
                get
                {
                    return mInstance.ContentManagedTiles;
                }
                set
                {
                    mInstance.ContentManagedTiles = value;
                }
            }


            /// <summary>
            /// Sort Newest Label.
            /// </summary>
            public string SortNewestLabel
            {
                get
                {
                    return mInstance.SortNewestLabel;
                }
                set
                {
                    mInstance.SortNewestLabel = value;
                }
            }


            /// <summary>
            /// Sort Oldest Label.
            /// </summary>
            public string SortOldestLabel
            {
                get
                {
                    return mInstance.SortOldestLabel;
                }
                set
                {
                    mInstance.SortOldestLabel = value;
                }
            }


            /// <summary>
            /// Tiles Label.
            /// </summary>
            public string TilesLabel
            {
                get
                {
                    return mInstance.TilesLabel;
                }
                set
                {
                    mInstance.TilesLabel = value;
                }
            }


            /// <summary>
            /// View All Label.
            /// </summary>
            public string ViewAllLabel
            {
                get
                {
                    return mInstance.ViewAllLabel;
                }
                set
                {
                    mInstance.ViewAllLabel = value;
                }
            }


            /// <summary>
            /// Posted Label.
            /// </summary>
            public string PostedLabel
            {
                get
                {
                    return mInstance.PostedLabel;
                }
                set
                {
                    mInstance.PostedLabel = value;
                }
            }


            /// <summary>
            /// Read More Label.
            /// </summary>
            public string ReadMoreLabel
            {
                get
                {
                    return mInstance.ReadMoreLabel;
                }
                set
                {
                    mInstance.ReadMoreLabel = value;
                }
            }


            /// <summary>
            /// All News Events Selector Value.
            /// </summary>
            public string AllNewsEventsSelectorValue
            {
                get
                {
                    return mInstance.AllNewsEventsSelectorValue;
                }
                set
                {
                    mInstance.AllNewsEventsSelectorValue = value;
                }
            }


            /// <summary>
            /// News Selector Value.
            /// </summary>
            public string NewsSelectorValue
            {
                get
                {
                    return mInstance.NewsSelectorValue;
                }
                set
                {
                    mInstance.NewsSelectorValue = value;
                }
            }


            /// <summary>
            /// Events Selector Value.
            /// </summary>
            public string EventsSelectorValue
            {
                get
                {
                    return mInstance.EventsSelectorValue;
                }
                set
                {
                    mInstance.EventsSelectorValue = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="NewsAndEventsPage" /> class.
        /// </summary>
        public NewsAndEventsPage()
            : base( CLASS_NAME )
        {
            mFields = new NewsAndEventsPageFields( this );
        }

        #endregion
    }
}