//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType( InsightsResources.CLASS_NAME, typeof( InsightsResources ) )]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Represents a content item of type InsightsResources.
    /// </summary>
    public partial class InsightsResources : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "custom.InsightsResources";


        /// <summary>
        /// The instance of the class that provides extended API for working with InsightsResources fields.
        /// </summary>
        private readonly InsightsResourcesFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// InsightsResourcesID.
        /// </summary>
        [DatabaseIDField]
        public int InsightsResourcesID
        {
            get
            {
                return ValidationHelper.GetInteger( GetValue( "InsightsResourcesID" ), 0 );
            }
            set
            {
                SetValue( "InsightsResourcesID", value );
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string HomeTitle
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "HomeTitle" ), "" );
            }
            set
            {
                SetValue( "HomeTitle", value );
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "Title" ), "" );
            }
            set
            {
                SetValue( "Title", value );
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "Description" ), "" );
            }
            set
            {
                SetValue( "Description", value );
            }
        }


        /// <summary>
        /// Hero Image.
        /// </summary>
        [DatabaseField]
        public string HeroImage
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "HeroImage" ), "" );
            }
            set
            {
                SetValue( "HeroImage", value );
            }
        }


        /// <summary>
        /// Headline.
        /// </summary>
        [DatabaseField]
        public string Headline
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "Headline" ), "" );
            }
            set
            {
                SetValue( "Headline", value );
            }
        }


        /// <summary>
        /// Subheadline.
        /// </summary>
        [DatabaseField]
        public string Subheadline
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "Subheadline" ), "" );
            }
            set
            {
                SetValue( "Subheadline", value );
            }
        }


        /// <summary>
        /// View All Label.
        /// </summary>
        [DatabaseField]
        public string ViewAllLabel
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "ViewAllLabel" ), "" );
            }
            set
            {
                SetValue( "ViewAllLabel", value );
            }
        }


        /// <summary>
        /// Product Data Sheets Title.
        /// </summary>
        [DatabaseField]
        public string ProductDataSheetsTitle
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "ProductDataSheetsTitle" ), "" );
            }
            set
            {
                SetValue( "ProductDataSheetsTitle", value );
            }
        }


        /// <summary>
        /// Stay Informed Tile Title.
        /// </summary>
        [DatabaseField]
        public string StayInformedTileTitle
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "StayInformedTileTitle" ), "" );
            }
            set
            {
                SetValue( "StayInformedTileTitle", value );
            }
        }


        /// <summary>
        /// Stay Informed Tile Description.
        /// </summary>
        [DatabaseField]
        public string StayInformedTileDescription
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "StayInformedTileDescription" ), "" );
            }
            set
            {
                SetValue( "StayInformedTileDescription", value );
            }
        }


        /// <summary>
        /// Featured Content List.
        /// </summary>
        [DatabaseField]
        public string FeaturedContentList
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "FeaturedContentList" ), "" );
            }
            set
            {
                SetValue( "FeaturedContentList", value );
            }
        }


        /// <summary>
        /// Sidebar Component Items.
        /// </summary>
        [DatabaseField]
        public string SidebarItems
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "SidebarItems" ), "" );
            }
            set
            {
                SetValue( "SidebarItems", value );
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with InsightsResources fields.
        /// </summary>
        public InsightsResourcesFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with InsightsResources fields.
        /// </summary>
        public partial class InsightsResourcesFields
        {
            /// <summary>
            /// The content item of type InsightsResources that is a target of the extended API.
            /// </summary>
            private readonly InsightsResources mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="InsightsResourcesFields" /> class with the specified content item of type InsightsResources.
            /// </summary>
            /// <param name="instance">The content item of type InsightsResources that is a target of the extended API.</param>
            public InsightsResourcesFields( InsightsResources instance )
            {
                mInstance = instance;
            }


            /// <summary>
            /// InsightsResourcesID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.InsightsResourcesID;
                }
                set
                {
                    mInstance.InsightsResourcesID = value;
                }
            }


            /// <summary>
            /// 
            /// </summary>
            public string HomeTitle
            {
                get
                {
                    return mInstance.HomeTitle;
                }
                set
                {
                    mInstance.HomeTitle = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.Description;
                }
                set
                {
                    mInstance.Description = value;
                }
            }


            /// <summary>
            /// Hero Image.
            /// </summary>
            public string HeroImage
            {
                get
                {
                    return mInstance.HeroImage;
                }
                set
                {
                    mInstance.HeroImage = value;
                }
            }


            /// <summary>
            /// Headline.
            /// </summary>
            public string Headline
            {
                get
                {
                    return mInstance.Headline;
                }
                set
                {
                    mInstance.Headline = value;
                }
            }


            /// <summary>
            /// Subheadline.
            /// </summary>
            public string Subheadline
            {
                get
                {
                    return mInstance.Subheadline;
                }
                set
                {
                    mInstance.Subheadline = value;
                }
            }


            /// <summary>
            /// View All Label.
            /// </summary>
            public string ViewAllLabel
            {
                get
                {
                    return mInstance.ViewAllLabel;
                }
                set
                {
                    mInstance.ViewAllLabel = value;
                }
            }


            /// <summary>
            /// Product Data Sheets Title.
            /// </summary>
            public string ProductDataSheetsTitle
            {
                get
                {
                    return mInstance.ProductDataSheetsTitle;
                }
                set
                {
                    mInstance.ProductDataSheetsTitle = value;
                }
            }


            /// <summary>
            /// Stay Informed Tile Title.
            /// </summary>
            public string StayInformedTileTitle
            {
                get
                {
                    return mInstance.StayInformedTileTitle;
                }
                set
                {
                    mInstance.StayInformedTileTitle = value;
                }
            }


            /// <summary>
            /// Stay Informed Tile Description.
            /// </summary>
            public string StayInformedTileDescription
            {
                get
                {
                    return mInstance.StayInformedTileDescription;
                }
                set
                {
                    mInstance.StayInformedTileDescription = value;
                }
            }


            /// <summary>
            /// Featured Content List.
            /// </summary>
            public string FeaturedContentList
            {
                get
                {
                    return mInstance.FeaturedContentList;
                }
                set
                {
                    mInstance.FeaturedContentList = value;
                }
            }


            /// <summary>
            /// Featured Content List.
            /// </summary>
            public IEnumerable<TreeNode> FeaturedContentList2
            {
                get
                {
                    return mInstance.GetRelatedDocuments( "FeaturedContentList2" );
                }
            }


            /// <summary>
            /// Sidebar Component Items.
            /// </summary>
            public string SidebarItems
            {
                get
                {
                    return mInstance.SidebarItems;
                }
                set
                {
                    mInstance.SidebarItems = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="InsightsResources" /> class.
        /// </summary>
        public InsightsResources()
            : base( CLASS_NAME )
        {
            mFields = new InsightsResourcesFields( this );
        }

        #endregion
    }
}