//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Privacyconstants.CLASS_NAME, typeof(Privacyconstants))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Represents a content item of type Privacyconstants.
    /// </summary>
    public partial class Privacyconstants : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "custom.privacyconstants";


        /// <summary>
        /// The instance of the class that provides extended API for working with Privacyconstants fields.
        /// </summary>
        private readonly PrivacyconstantsFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// PrivacyconstantsID.
        /// </summary>
        [DatabaseIDField]
        public int PrivacyconstantsID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("PrivacyconstantsID"), 0);
            }
            set
            {
                SetValue("PrivacyconstantsID", value);
            }
        }


        /// <summary>
        /// Privacy Header.
        /// </summary>
        [DatabaseField]
        public string PrivacyHeader
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PrivacyHeader"), "Privacy Statement");
            }
            set
            {
                SetValue("PrivacyHeader", value);
            }
        }


        /// <summary>
        /// Privacy Content.
        /// </summary>
        [DatabaseField]
        public string PrivacyContent
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PrivacyContent"), "");
            }
            set
            {
                SetValue("PrivacyContent", value);
            }
        }


        /// <summary>
        /// Cookie Header.
        /// </summary>
        [DatabaseField]
        public string CookieHeader
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CookieHeader"), "Cookie Policy");
            }
            set
            {
                SetValue("CookieHeader", value);
            }
        }


        /// <summary>
        /// Cookie Content.
        /// </summary>
        [DatabaseField]
        public string CookieContent
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CookieContent"), "");
            }
            set
            {
                SetValue("CookieContent", value);
            }
        }


        /// <summary>
        /// Preference Cookie Header.
        /// </summary>
        [DatabaseField]
        public string PrefCookieHeader
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PrefCookieHeader"), "Preference Cookies");
            }
            set
            {
                SetValue("PrefCookieHeader", value);
            }
        }


        /// <summary>
        /// Preference Cookie Message.
        /// </summary>
        [DatabaseField]
        public string PrefCookieMessage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PrefCookieMessage"), "");
            }
            set
            {
                SetValue("PrefCookieMessage", value);
            }
        }


        /// <summary>
        /// Performance Cookie Header.
        /// </summary>
        [DatabaseField]
        public string PerfCookieHeader
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PerfCookieHeader"), "Performance Cookies");
            }
            set
            {
                SetValue("PerfCookieHeader", value);
            }
        }


        /// <summary>
        /// Performance Cookie Message.
        /// </summary>
        [DatabaseField]
        public string PerfCookieMessage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PerfCookieMessage"), "");
            }
            set
            {
                SetValue("PerfCookieMessage", value);
            }
        }


        /// <summary>
        /// Personalization Cookie Header.
        /// </summary>
        [DatabaseField]
        public string PersonCookieHeader
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PersonCookieHeader"), "Personalization Cookies");
            }
            set
            {
                SetValue("PersonCookieHeader", value);
            }
        }


        /// <summary>
        /// Personalization Cookie Message.
        /// </summary>
        [DatabaseField]
        public string PersonCookieMessage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PersonCookieMessage"), "");
            }
            set
            {
                SetValue("PersonCookieMessage", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with Privacyconstants fields.
        /// </summary>
        public PrivacyconstantsFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with Privacyconstants fields.
        /// </summary>
        public partial class PrivacyconstantsFields
        {
            /// <summary>
            /// The content item of type Privacyconstants that is a target of the extended API.
            /// </summary>
            private readonly Privacyconstants mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="PrivacyconstantsFields" /> class with the specified content item of type Privacyconstants.
            /// </summary>
            /// <param name="instance">The content item of type Privacyconstants that is a target of the extended API.</param>
            public PrivacyconstantsFields(Privacyconstants instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// PrivacyconstantsID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.PrivacyconstantsID;
                }
                set
                {
                    mInstance.PrivacyconstantsID = value;
                }
            }


            /// <summary>
            /// Privacy Header.
            /// </summary>
            public string PrivacyHeader
            {
                get
                {
                    return mInstance.PrivacyHeader;
                }
                set
                {
                    mInstance.PrivacyHeader = value;
                }
            }


            /// <summary>
            /// Privacy Content.
            /// </summary>
            public string PrivacyContent
            {
                get
                {
                    return mInstance.PrivacyContent;
                }
                set
                {
                    mInstance.PrivacyContent = value;
                }
            }


            /// <summary>
            /// Privacy Sidebar.
            /// </summary>
            public IEnumerable<TreeNode> PrivacySidebar
            {
                get
                {
                    return mInstance.GetRelatedDocuments("PrivacySidebar");
                }
            }


            /// <summary>
            /// Cookie Header.
            /// </summary>
            public string CookieHeader
            {
                get
                {
                    return mInstance.CookieHeader;
                }
                set
                {
                    mInstance.CookieHeader = value;
                }
            }


            /// <summary>
            /// Cookie Content.
            /// </summary>
            public string CookieContent
            {
                get
                {
                    return mInstance.CookieContent;
                }
                set
                {
                    mInstance.CookieContent = value;
                }
            }


            /// <summary>
            /// Preference Cookie Header.
            /// </summary>
            public string PrefCookieHeader
            {
                get
                {
                    return mInstance.PrefCookieHeader;
                }
                set
                {
                    mInstance.PrefCookieHeader = value;
                }
            }


            /// <summary>
            /// Preference Cookie Message.
            /// </summary>
            public string PrefCookieMessage
            {
                get
                {
                    return mInstance.PrefCookieMessage;
                }
                set
                {
                    mInstance.PrefCookieMessage = value;
                }
            }


            /// <summary>
            /// Performance Cookie Header.
            /// </summary>
            public string PerfCookieHeader
            {
                get
                {
                    return mInstance.PerfCookieHeader;
                }
                set
                {
                    mInstance.PerfCookieHeader = value;
                }
            }


            /// <summary>
            /// Performance Cookie Message.
            /// </summary>
            public string PerfCookieMessage
            {
                get
                {
                    return mInstance.PerfCookieMessage;
                }
                set
                {
                    mInstance.PerfCookieMessage = value;
                }
            }


            /// <summary>
            /// Personalization Cookie Header.
            /// </summary>
            public string PersonCookieHeader
            {
                get
                {
                    return mInstance.PersonCookieHeader;
                }
                set
                {
                    mInstance.PersonCookieHeader = value;
                }
            }


            /// <summary>
            /// Personalization Cookie Message.
            /// </summary>
            public string PersonCookieMessage
            {
                get
                {
                    return mInstance.PersonCookieMessage;
                }
                set
                {
                    mInstance.PersonCookieMessage = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="Privacyconstants" /> class.
        /// </summary>
        public Privacyconstants() : base(CLASS_NAME)
        {
            mFields = new PrivacyconstantsFields(this);
        }

        #endregion
    }
}