//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(CustomNews.CLASS_NAME, typeof(CustomNews))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Represents a content item of type CustomNews.
    /// </summary>
    public partial class CustomNews : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "custom.CustomNews";


        /// <summary>
        /// The instance of the class that provides extended API for working with CustomNews fields.
        /// </summary>
        private readonly CustomNewsFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// CustomNewsID.
        /// </summary>
        [DatabaseIDField]
        public int CustomNewsID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("CustomNewsID"), 0);
            }
            set
            {
                SetValue("CustomNewsID", value);
            }
        }


        /// <summary>
        /// Tile Title.
        /// </summary>
        [DatabaseField]
        public string TileTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TileTitle"), "");
            }
            set
            {
                SetValue("TileTitle", value);
            }
        }


        /// <summary>
        /// Image displayed on a tile.
        /// </summary>
        [DatabaseField]
        public string HomeImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomeImage"), "");
            }
            set
            {
                SetValue("HomeImage", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), "");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Text that appears on hover over the tile.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Description"), "");
            }
            set
            {
                SetValue("Description", value);
            }
        }


        /// <summary>
        /// Content.
        /// </summary>
        [DatabaseField]
        public string Copy
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Copy"), "");
            }
            set
            {
                SetValue("Copy", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public DateTime Date
        {
            get
            {
                return ValidationHelper.GetDateTime(GetValue("Date"), DateTimeHelper.ZERO_TIME);
            }
            set
            {
                SetValue("Date", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string Image
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Image"), "");
            }
            set
            {
                SetValue("Image", value);
            }
        }


        /// <summary>
        /// Sidebar Items.
        /// </summary>
        [DatabaseField]
        public string SidebarItems
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SidebarItems"), "");
            }
            set
            {
                SetValue("SidebarItems", value);
            }
        }


        /// <summary>
        /// PdfReference.
        /// </summary>
        [DatabaseField]
        public string PdfReference
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PdfReference"), "");
            }
            set
            {
                SetValue("PdfReference", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with CustomNews fields.
        /// </summary>
        public CustomNewsFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with CustomNews fields.
        /// </summary>
        public partial class CustomNewsFields
        {
            /// <summary>
            /// The content item of type CustomNews that is a target of the extended API.
            /// </summary>
            private readonly CustomNews mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="CustomNewsFields" /> class with the specified content item of type CustomNews.
            /// </summary>
            /// <param name="instance">The content item of type CustomNews that is a target of the extended API.</param>
            public CustomNewsFields(CustomNews instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// CustomNewsID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.CustomNewsID;
                }
                set
                {
                    mInstance.CustomNewsID = value;
                }
            }


            /// <summary>
            /// Tile Title.
            /// </summary>
            public string TileTitle
            {
                get
                {
                    return mInstance.TileTitle;
                }
                set
                {
                    mInstance.TileTitle = value;
                }
            }


            /// <summary>
            /// Image displayed on a tile.
            /// </summary>
            public string HomeImage
            {
                get
                {
                    return mInstance.HomeImage;
                }
                set
                {
                    mInstance.HomeImage = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Text that appears on hover over the tile.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.Description;
                }
                set
                {
                    mInstance.Description = value;
                }
            }


            /// <summary>
            /// Content.
            /// </summary>
            public string Copy
            {
                get
                {
                    return mInstance.Copy;
                }
                set
                {
                    mInstance.Copy = value;
                }
            }


            /// <summary>
            /// 
            /// </summary>
            public DateTime Date
            {
                get
                {
                    return mInstance.Date;
                }
                set
                {
                    mInstance.Date = value;
                }
            }


            /// <summary>
            /// 
            /// </summary>
            public string Image
            {
                get
                {
                    return mInstance.Image;
                }
                set
                {
                    mInstance.Image = value;
                }
            }


            /// <summary>
            /// Sidebar Items.
            /// </summary>
            public string SidebarItems
            {
                get
                {
                    return mInstance.SidebarItems;
                }
                set
                {
                    mInstance.SidebarItems = value;
                }
            }


            /// <summary>
            /// Sidebar Items.
            /// </summary>
            public IEnumerable<TreeNode> SidebarItems2
            {
                get
                {
                    return mInstance.GetRelatedDocuments("SidebarItems2");
                }
            }


            /// <summary>
            /// PdfReference.
            /// </summary>
            public string PdfReference
            {
                get
                {
                    return mInstance.PdfReference;
                }
                set
                {
                    mInstance.PdfReference = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomNews" /> class.
        /// </summary>
        public CustomNews()
            : base(CLASS_NAME)
        {
            mFields = new CustomNewsFields(this);
        }

        #endregion
    }
}