//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com. 
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Event.CLASS_NAME, typeof(Event))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Sample item class.
    /// </summary>
    public partial class Event : TreeNode
    {
        #region "Constants"

        /// <summary>
        /// Class name of the item.
        /// </summary>
        public const string CLASS_NAME = "custom.Event";

        #endregion


        #region "Properties"

        /// <summary>
        /// EventID.
        /// </summary>
        [DatabaseField]
        public int EventID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("EventID"), 0);
            }
            set
            {
                SetValue("EventID", value);
            }
        }


        /// <summary>
        /// Tile Title.
        /// </summary>
        [DatabaseField]
        public string TileTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TileTitle"), "");
            }
            set
            {
                SetValue("TileTitle", value);
            }
        }


        /// <summary>
        /// Date.
        /// </summary>
        [DatabaseField]
        public DateTime Date
        {
            get
            {
                return ValidationHelper.GetDateTime(GetValue("Date"), DateTimeHelper.ZERO_TIME);
            }
            set
            {
                SetValue("Date", value);
            }
        }


        /// <summary>
        /// Image displayed on a tile.
        /// </summary>
        [DatabaseField]
        public string HomeImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HomeImage"), "");
            }
            set
            {
                SetValue("HomeImage", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), "");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Text that appears on hover over the tile.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Description"), "");
            }
            set
            {
                SetValue("Description", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string Image
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Image"), "");
            }
            set
            {
                SetValue("Image", value);
            }
        }


        /// <summary>
        /// Location.
        /// </summary>
        [DatabaseField]
        public string Location
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Location"), "");
            }
            set
            {
                SetValue("Location", value);
            }
        }


        /// <summary>
        /// URL.
        /// </summary>
        [DatabaseField]
        public string URL
        {
            get
            {
                return ValidationHelper.GetString(GetValue("URL"), "");
            }
            set
            {
                SetValue("URL", value);
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Constructor.
        /// </summary>
        public Event()
            : base(CLASS_NAME)
        {
        }

        #endregion
    }
}
