//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com. 
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(GenericModel.CLASS_NAME, typeof(GenericModel))]

namespace CMS.DocumentEngine.Types
{
	/// <summary>
	/// Sample item class.
	/// </summary>
	public partial class GenericModel : TreeNode
	{
		#region "Constants"

		/// <summary>
		/// Class name of the item.
		/// </summary>
		public const string CLASS_NAME = "custom.GenericModel";

		#endregion


		#region "Properties"

		/// <summary>
		/// GenericModelID.
		/// </summary>
		[DatabaseField]
		public int GenericModelID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("GenericModelID"), 0);
			}
			set
			{
				SetValue("GenericModelID", value);
			}
		}


		/// <summary>
		/// ListingImage.
		/// </summary>
		[DatabaseField]
		public string ListingImage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ListingImage"), "");
			}
			set
			{
				SetValue("ListingImage", value);
			}
		}


		/// <summary>
		/// Abstract.
		/// </summary>
		[DatabaseField]
		public string Abstract
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Abstract"), "");
			}
			set
			{
				SetValue("Abstract", value);
			}
		}


		/// <summary>
		/// 
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), "");
			}
			set
			{
				SetValue("Title", value);
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Constructor.
		/// </summary>
		public GenericModel()
			: base(CLASS_NAME)
		{
		}

		#endregion
	}
}
