//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(PageTypeDisplayValue.CLASS_NAME, typeof(PageTypeDisplayValue))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Represents a content item of type PageTypeDisplayValue.
    /// </summary>
    public partial class PageTypeDisplayValue : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "custom.PageTypeDisplayValue";


        /// <summary>
        /// The instance of the class that provides extended API for working with PageTypeDisplayValue fields.
        /// </summary>
        private readonly PageTypeDisplayValueFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// PageTypeDisplayValuesID.
        /// </summary>
        [DatabaseIDField]
        public int PageTypeDisplayValuesID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("PageTypeDisplayValuesID"), 0);
            }
            set
            {
                SetValue("PageTypeDisplayValuesID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), "");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Display Value.
        /// </summary>
        [DatabaseField]
        public string DisplayValue
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DisplayValue"), "");
            }
            set
            {
                SetValue("DisplayValue", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with PageTypeDisplayValue fields.
        /// </summary>
        public PageTypeDisplayValueFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with PageTypeDisplayValue fields.
        /// </summary>
        public partial class PageTypeDisplayValueFields
        {
            /// <summary>
            /// The content item of type PageTypeDisplayValue that is a target of the extended API.
            /// </summary>
            private readonly PageTypeDisplayValue mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="PageTypeDisplayValueFields" /> class with the specified content item of type PageTypeDisplayValue.
            /// </summary>
            /// <param name="instance">The content item of type PageTypeDisplayValue that is a target of the extended API.</param>
            public PageTypeDisplayValueFields(PageTypeDisplayValue instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// PageTypeDisplayValuesID.
            /// </summary>
            public int sID
            {
                get
                {
                    return mInstance.PageTypeDisplayValuesID;
                }
                set
                {
                    mInstance.PageTypeDisplayValuesID = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Display Value.
            /// </summary>
            public string DisplayValue
            {
                get
                {
                    return mInstance.DisplayValue;
                }
                set
                {
                    mInstance.DisplayValue = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="PageTypeDisplayValue" /> class.
        /// </summary>
        public PageTypeDisplayValue()
            : base(CLASS_NAME)
        {
            mFields = new PageTypeDisplayValueFields(this);
        }

        #endregion
    }
}