//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType( PersonalizedTile.CLASS_NAME, typeof( PersonalizedTile ) )]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Represents a content item of type PersonalizedTile.
    /// </summary>
    public partial class PersonalizedTile : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "custom.PersonalizedTile";


        /// <summary>
        /// The instance of the class that provides extended API for working with PersonalizedTile fields.
        /// </summary>
        private readonly PersonalizedTileFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// PersonalizedTileID.
        /// </summary>
        [DatabaseIDField]
        public int PersonalizedTileID
        {
            get
            {
                return ValidationHelper.GetInteger( GetValue( "PersonalizedTileID" ), 0 );
            }
            set
            {
                SetValue( "PersonalizedTileID", value );
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string HomeTitle
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "HomeTitle" ), "" );
            }
            set
            {
                SetValue( "HomeTitle", value );
            }
        }


        /// <summary>
        /// Tile Title.
        /// </summary>
        [DatabaseField]
        public string TileTitle
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "TileTitle" ), "" );
            }
            set
            {
                SetValue( "TileTitle", value );
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "Title" ), "" );
            }
            set
            {
                SetValue( "Title", value );
            }
        }


        /// <summary>
        /// Image displayed on a tile.
        /// </summary>
        [DatabaseField]
        public string HomeImage
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "HomeImage" ), "" );
            }
            set
            {
                SetValue( "HomeImage", value );
            }
        }


        /// <summary>
        /// Text that appears on hover over the tile.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "Description" ), "" );
            }
            set
            {
                SetValue( "Description", value );
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with PersonalizedTile fields.
        /// </summary>
        public PersonalizedTileFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with PersonalizedTile fields.
        /// </summary>
        public partial class PersonalizedTileFields
        {
            /// <summary>
            /// The content item of type PersonalizedTile that is a target of the extended API.
            /// </summary>
            private readonly PersonalizedTile mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="PersonalizedTileFields" /> class with the specified content item of type PersonalizedTile.
            /// </summary>
            /// <param name="instance">The content item of type PersonalizedTile that is a target of the extended API.</param>
            public PersonalizedTileFields( PersonalizedTile instance )
            {
                mInstance = instance;
            }


            /// <summary>
            /// PersonalizedTileID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.PersonalizedTileID;
                }
                set
                {
                    mInstance.PersonalizedTileID = value;
                }
            }


            /// <summary>
            /// 
            /// </summary>
            public string HomeTitle
            {
                get
                {
                    return mInstance.HomeTitle;
                }
                set
                {
                    mInstance.HomeTitle = value;
                }
            }


            /// <summary>
            /// Tile Title.
            /// </summary>
            public string TileTitle
            {
                get
                {
                    return mInstance.TileTitle;
                }
                set
                {
                    mInstance.TileTitle = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Image displayed on a tile.
            /// </summary>
            public string HomeImage
            {
                get
                {
                    return mInstance.HomeImage;
                }
                set
                {
                    mInstance.HomeImage = value;
                }
            }


            /// <summary>
            /// Text that appears on hover over the tile.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.Description;
                }
                set
                {
                    mInstance.Description = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="PersonalizedTile" /> class.
        /// </summary>
        public PersonalizedTile()
            : base( CLASS_NAME )
        {
            mFields = new PersonalizedTileFields( this );
        }

        #endregion
    }
}