//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com. 
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(PersonalizationSettings.CLASS_NAME, typeof(PersonalizationSettings))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Sample item class.
    /// </summary>
    public partial class PersonalizationSettings : TreeNode
    {
        #region "Constants"

        /// <summary>
        /// Class name of the item.
        /// </summary>
        public const string CLASS_NAME = "custom.PersonalizationSettings";

        #endregion


        #region "Properties"

        /// <summary>
        /// PersonalizationSettingsID.
        /// </summary>
        [DatabaseField]
        public int PersonalizationSettingsID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("PersonalizationSettingsID"), 0);
            }
            set
            {
                SetValue("PersonalizationSettingsID", value);
            }
        }


        /// <summary>
        /// Personalization Section Title.
        /// </summary>
        [DatabaseField]
        public string PersonalizationSectionTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PersonalizationSectionTitle"), "");
            }
            set
            {
                SetValue("PersonalizationSectionTitle", value);
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Constructor.
        /// </summary>
        public PersonalizationSettings()
            : base(CLASS_NAME)
        {
        }

        #endregion
    }
}
