//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com. 
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(PersonalizedContentModel.CLASS_NAME, typeof(PersonalizedContentModel))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Sample item class.
    /// </summary>
    public partial class PersonalizedContentModel : TreeNode
    {
        #region "Constants"

        /// <summary>
        /// Class name of the item.
        /// </summary>
        public const string CLASS_NAME = "custom.PersonalizedContentModel";

        #endregion


        #region "Properties"

        /// <summary>
        /// PersonalizedContentModelID.
        /// </summary>
        [DatabaseField]
        public int PersonalizedContentModelID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("PersonalizedContentModelID"), 0);
            }
            set
            {
                SetValue("PersonalizedContentModelID", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public string Persona
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Persona"), "");
            }
            set
            {
                SetValue("Persona", value);
            }
        }


        /// <summary>
        /// Documents.
        /// </summary>
        [DatabaseField]
        public string Documents
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Documents"), "");
            }
            set
            {
                SetValue("Documents", value);
            }
        }


        /// <summary>
        /// Default.
        /// </summary>
        [DatabaseField]
        public bool Default
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("Default"), false);
            }
            set
            {
                SetValue("Default", value);
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Constructor.
        /// </summary>
        public PersonalizedContentModel()
            : base(CLASS_NAME)
        {
        }

        #endregion
    }
}
