//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com. 
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(PersonalizationCategoryPointsModel.CLASS_NAME, typeof(PersonalizationCategoryPointsModel))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Sample item class.
    /// </summary>
    public partial class PersonalizationCategoryPointsModel : TreeNode
    {
        #region "Constants"

        /// <summary>
        /// Class name of the item.
        /// </summary>
        public const string CLASS_NAME = "custom.PersonalizationCategoryPointsModel";

        #endregion


        #region "Properties"

        /// <summary>
        /// PersonalizationCategoryPointsModelID.
        /// </summary>
        [DatabaseField]
        public int PersonalizationCategoryPointsModelID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("PersonalizationCategoryPointsModelID"), 0);
            }
            set
            {
                SetValue("PersonalizationCategoryPointsModelID", value);
            }
        }


        /// <summary>
        /// Document ID.
        /// </summary>
        [DatabaseField]
        public string AftonDocumentId
        {
            get
            {
                return ValidationHelper.GetString(GetValue("AftonDocumentId"), "");
            }
            set
            {
                SetValue("AftonDocumentId", value);
            }
        }


        /// <summary>
        /// Document Category.
        /// </summary>
        [DatabaseField]
        public string DocumentCategory
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DocumentCategory"), "");
            }
            set
            {
                SetValue("DocumentCategory", value);
            }
        }


        /// <summary>
        /// 
        /// </summary>
        [DatabaseField]
        public int PointValue
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("PointValue"), 0);
            }
            set
            {
                SetValue("PointValue", value);
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Constructor.
        /// </summary>
        public PersonalizationCategoryPointsModel()
            : base(CLASS_NAME)
        {
        }

        #endregion
    }
}
