//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(ContactPage.CLASS_NAME, typeof(ContactPage))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Represents a content item of type ContactPage.
    /// </summary>
    public partial class ContactPage : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "custom.ContactPage";


        /// <summary>
        /// The instance of the class that provides extended API for working with ContactPage fields.
        /// </summary>
        private readonly ContactPageFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// ContactPageID.
        /// </summary>
        [DatabaseIDField]
        public int ContactPageID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("ContactPageID"), 0);
            }
            set
            {
                SetValue("ContactPageID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), "");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Description"), "");
            }
            set
            {
                SetValue("Description", value);
            }
        }


        /// <summary>
        /// First Name Placeholder.
        /// </summary>
        [DatabaseField]
        public string FirstNamePlaceholder
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FirstNamePlaceholder"), "");
            }
            set
            {
                SetValue("FirstNamePlaceholder", value);
            }
        }


        /// <summary>
        /// Last Name Placeholder.
        /// </summary>
        [DatabaseField]
        public string LastNamePlaceholder
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LastNamePlaceholder"), "");
            }
            set
            {
                SetValue("LastNamePlaceholder", value);
            }
        }


        /// <summary>
        /// Company Name Placeholder.
        /// </summary>
        [DatabaseField]
        public string CompanyNamePlaceholder
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CompanyNamePlaceholder"), "");
            }
            set
            {
                SetValue("CompanyNamePlaceholder", value);
            }
        }


        /// <summary>
        /// Email Placeholder.
        /// </summary>
        [DatabaseField]
        public string EmailPlaceholder
        {
            get
            {
                return ValidationHelper.GetString(GetValue("EmailPlaceholder"), "");
            }
            set
            {
                SetValue("EmailPlaceholder", value);
            }
        }


        /// <summary>
        /// Phone Placeholder.
        /// </summary>
        [DatabaseField]
        public string PhonePlaceholder
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PhonePlaceholder"), "");
            }
            set
            {
                SetValue("PhonePlaceholder", value);
            }
        }


        /// <summary>
        /// Select Country Placeholder.
        /// </summary>
        [DatabaseField]
        public string SelectCountryPlaceholder
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SelectCountryPlaceholder"), "");
            }
            set
            {
                SetValue("SelectCountryPlaceholder", value);
            }
        }


        /// <summary>
        /// Message Placeholder.
        /// </summary>
        [DatabaseField]
        public string MessagePlaceholder
        {
            get
            {
                return ValidationHelper.GetString(GetValue("MessagePlaceholder"), "");
            }
            set
            {
                SetValue("MessagePlaceholder", value);
            }
        }


        /// <summary>
        /// Newsletter Title.
        /// </summary>
        [DatabaseField]
        public string NewsletterTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("NewsletterTitle"), "");
            }
            set
            {
                SetValue("NewsletterTitle", value);
            }
        }


        /// <summary>
        /// Newsletter Checkbox Label.
        /// </summary>
        [DatabaseField]
        public string NewsletterCheckboxLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("NewsletterCheckboxLabel"), "");
            }
            set
            {
                SetValue("NewsletterCheckboxLabel", value);
            }
        }


        /// <summary>
        /// Submit Label.
        /// </summary>
        [DatabaseField]
        public string SubmitLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SubmitLabel"), "");
            }
            set
            {
                SetValue("SubmitLabel", value);
            }
        }


        /// <summary>
        /// Prompt Label.
        /// </summary>
        [DatabaseField]
        public string PromptLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PromptLabel"), "");
            }
            set
            {
                SetValue("PromptLabel", value);
            }
        }


        /// <summary>
        /// View Sales Offices Label.
        /// </summary>
        [DatabaseField]
        public string ViewSalesOfficesLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ViewSalesOfficesLabel"), "");
            }
            set
            {
                SetValue("ViewSalesOfficesLabel", value);
            }
        }


        /// <summary>
        /// Thank You Header.
        /// </summary>
        [DatabaseField]
        public string ThankYouHeader
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ThankYouHeader"), "");
            }
            set
            {
                SetValue("ThankYouHeader", value);
            }
        }


        /// <summary>
        /// Thank You Message.
        /// </summary>
        [DatabaseField]
        public string ThankYouMessage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ThankYouMessage"), "");
            }
            set
            {
                SetValue("ThankYouMessage", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with ContactPage fields.
        /// </summary>
        public ContactPageFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with ContactPage fields.
        /// </summary>
        public partial class ContactPageFields
        {
            /// <summary>
            /// The content item of type ContactPage that is a target of the extended API.
            /// </summary>
            private readonly ContactPage mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="ContactPageFields" /> class with the specified content item of type ContactPage.
            /// </summary>
            /// <param name="instance">The content item of type ContactPage that is a target of the extended API.</param>
            public ContactPageFields(ContactPage instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// ContactPageID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.ContactPageID;
                }
                set
                {
                    mInstance.ContactPageID = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.Description;
                }
                set
                {
                    mInstance.Description = value;
                }
            }


            /// <summary>
            /// First Name Placeholder.
            /// </summary>
            public string FirstNamePlaceholder
            {
                get
                {
                    return mInstance.FirstNamePlaceholder;
                }
                set
                {
                    mInstance.FirstNamePlaceholder = value;
                }
            }


            /// <summary>
            /// Last Name Placeholder.
            /// </summary>
            public string LastNamePlaceholder
            {
                get
                {
                    return mInstance.LastNamePlaceholder;
                }
                set
                {
                    mInstance.LastNamePlaceholder = value;
                }
            }


            /// <summary>
            /// Company Name Placeholder.
            /// </summary>
            public string CompanyNamePlaceholder
            {
                get
                {
                    return mInstance.CompanyNamePlaceholder;
                }
                set
                {
                    mInstance.CompanyNamePlaceholder = value;
                }
            }


            /// <summary>
            /// Email Placeholder.
            /// </summary>
            public string EmailPlaceholder
            {
                get
                {
                    return mInstance.EmailPlaceholder;
                }
                set
                {
                    mInstance.EmailPlaceholder = value;
                }
            }


            /// <summary>
            /// Phone Placeholder.
            /// </summary>
            public string PhonePlaceholder
            {
                get
                {
                    return mInstance.PhonePlaceholder;
                }
                set
                {
                    mInstance.PhonePlaceholder = value;
                }
            }


            /// <summary>
            /// Select Country Placeholder.
            /// </summary>
            public string SelectCountryPlaceholder
            {
                get
                {
                    return mInstance.SelectCountryPlaceholder;
                }
                set
                {
                    mInstance.SelectCountryPlaceholder = value;
                }
            }


            /// <summary>
            /// Message Placeholder.
            /// </summary>
            public string MessagePlaceholder
            {
                get
                {
                    return mInstance.MessagePlaceholder;
                }
                set
                {
                    mInstance.MessagePlaceholder = value;
                }
            }


            /// <summary>
            /// Newsletter Title.
            /// </summary>
            public string NewsletterTitle
            {
                get
                {
                    return mInstance.NewsletterTitle;
                }
                set
                {
                    mInstance.NewsletterTitle = value;
                }
            }


            /// <summary>
            /// Newsletter Checkbox Label.
            /// </summary>
            public string NewsletterCheckboxLabel
            {
                get
                {
                    return mInstance.NewsletterCheckboxLabel;
                }
                set
                {
                    mInstance.NewsletterCheckboxLabel = value;
                }
            }


            /// <summary>
            /// Submit Label.
            /// </summary>
            public string SubmitLabel
            {
                get
                {
                    return mInstance.SubmitLabel;
                }
                set
                {
                    mInstance.SubmitLabel = value;
                }
            }


            /// <summary>
            /// Prompt Label.
            /// </summary>
            public string PromptLabel
            {
                get
                {
                    return mInstance.PromptLabel;
                }
                set
                {
                    mInstance.PromptLabel = value;
                }
            }


            /// <summary>
            /// View Sales Offices Label.
            /// </summary>
            public string ViewSalesOfficesLabel
            {
                get
                {
                    return mInstance.ViewSalesOfficesLabel;
                }
                set
                {
                    mInstance.ViewSalesOfficesLabel = value;
                }
            }


            /// <summary>
            /// Thank You Header.
            /// </summary>
            public string ThankYouHeader
            {
                get
                {
                    return mInstance.ThankYouHeader;
                }
                set
                {
                    mInstance.ThankYouHeader = value;
                }
            }


            /// <summary>
            /// Thank You Message.
            /// </summary>
            public string ThankYouMessage
            {
                get
                {
                    return mInstance.ThankYouMessage;
                }
                set
                {
                    mInstance.ThankYouMessage = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactPage" /> class.
        /// </summary>
        public ContactPage()
            : base(CLASS_NAME)
        {
            mFields = new ContactPageFields(this);
        }

        #endregion
    }
}