//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com. 
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(ContactPage.CLASS_NAME, typeof(ContactPage))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Sample item class.
    /// </summary>
    public partial class ContactPage : TreeNode
    {
        #region "Constants"

        /// <summary>
        /// Class name of the item.
        /// </summary>
        public const string CLASS_NAME = "custom.ContactPage";

        #endregion


        #region "Properties"

        /// <summary>
        /// ContactPageID.
        /// </summary>
        [DatabaseField]
        public int ContactPageID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("ContactPageID"), 0);
            }
            set
            {
                SetValue("ContactPageID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), "");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Form Introducion Text.
        /// </summary>
        [DatabaseField]
        public string FormIntroducionText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FormIntroducionText"), "");
            }
            set
            {
                SetValue("FormIntroducionText", value);
            }
        }


        /// <summary>
        /// First Name Placeholder.
        /// </summary>
        [DatabaseField]
        public string FirstNamePlaceholder
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FirstNamePlaceholder"), "");
            }
            set
            {
                SetValue("FirstNamePlaceholder", value);
            }
        }


        /// <summary>
        /// Last Name Placeholder.
        /// </summary>
        [DatabaseField]
        public string LastNamePlaceholder
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LastNamePlaceholder"), "");
            }
            set
            {
                SetValue("LastNamePlaceholder", value);
            }
        }


        /// <summary>
        /// Company Name Placeholder.
        /// </summary>
        [DatabaseField]
        public string CompanyNamePlaceholder
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CompanyNamePlaceholder"), "");
            }
            set
            {
                SetValue("CompanyNamePlaceholder", value);
            }
        }


        /// <summary>
        /// Email Placeholder.
        /// </summary>
        [DatabaseField]
        public string EmailPlaceholder
        {
            get
            {
                return ValidationHelper.GetString(GetValue("EmailPlaceholder"), "");
            }
            set
            {
                SetValue("EmailPlaceholder", value);
            }
        }


        /// <summary>
        /// Phone Placeholder.
        /// </summary>
        [DatabaseField]
        public string PhonePlaceholder
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PhonePlaceholder"), "");
            }
            set
            {
                SetValue("PhonePlaceholder", value);
            }
        }


        /// <summary>
        /// Select Country Placeholder.
        /// </summary>
        [DatabaseField]
        public string SelectCountryPlaceholder
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SelectCountryPlaceholder"), "");
            }
            set
            {
                SetValue("SelectCountryPlaceholder", value);
            }
        }


        /// <summary>
        /// Message Placeholder.
        /// </summary>
        [DatabaseField]
        public string MessagePlaceholder
        {
            get
            {
                return ValidationHelper.GetString(GetValue("MessagePlaceholder"), "");
            }
            set
            {
                SetValue("MessagePlaceholder", value);
            }
        }


        /// <summary>
        /// Newsletter Title.
        /// </summary>
        [DatabaseField]
        public string NewsletterTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("NewsletterTitle"), "");
            }
            set
            {
                SetValue("NewsletterTitle", value);
            }
        }


        /// <summary>
        /// Newsletter Checkbox Label.
        /// </summary>
        [DatabaseField]
        public string NewsletterCheckboxLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("NewsletterCheckboxLabel"), "");
            }
            set
            {
                SetValue("NewsletterCheckboxLabel", value);
            }
        }


        /// <summary>
        /// Submit Label.
        /// </summary>
        [DatabaseField]
        public string SubmitLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SubmitLabel"), "");
            }
            set
            {
                SetValue("SubmitLabel", value);
            }
        }


        /// <summary>
        /// Prompt Label.
        /// </summary>
        [DatabaseField]
        public string PromptLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PromptLabel"), "");
            }
            set
            {
                SetValue("PromptLabel", value);
            }
        }


        /// <summary>
        /// View Sales Offices Label.
        /// </summary>
        [DatabaseField]
        public string ViewSalesOfficesLabel
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ViewSalesOfficesLabel"), "");
            }
            set
            {
                SetValue("ViewSalesOfficesLabel", value);
            }
        }


        /// <summary>
        /// Emergency Response Title.
        /// </summary>
        [DatabaseField]
        public string EmergencyResponseTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("EmergencyResponseTitle"), "");
            }
            set
            {
                SetValue("EmergencyResponseTitle", value);
            }
        }


        /// <summary>
        /// Emergency Response Body.
        /// </summary>
        [DatabaseField]
        public string EmergencyResponseBody
        {
            get
            {
                return ValidationHelper.GetString(GetValue("EmergencyResponseBody"), "");
            }
            set
            {
                SetValue("EmergencyResponseBody", value);
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Constructor.
        /// </summary>
        public ContactPage()
            : base(CLASS_NAME)
        {
        }

        #endregion
    }
}
