//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com. 
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(SalesOffice.CLASS_NAME, typeof(SalesOffice))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Sample item class.
    /// </summary>
    public partial class SalesOffice : TreeNode
    {
        #region "Constants"

        /// <summary>
        /// Class name of the item.
        /// </summary>
        public const string CLASS_NAME = "custom.SalesOffice";

        #endregion


        #region "Properties"

        /// <summary>
        /// SalesOfficeID.
        /// </summary>
        [DatabaseField]
        public int SalesOfficeID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("SalesOfficeID"), 0);
            }
            set
            {
                SetValue("SalesOfficeID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), "");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Address.
        /// </summary>
        [DatabaseField]
        public string Address
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Address"), "");
            }
            set
            {
                SetValue("Address", value);
            }
        }


        /// <summary>
        /// Country.
        /// </summary>
        [DatabaseField]
        public string Country
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Country"), "");
            }
            set
            {
                SetValue("Country", value);
            }
        }


        /// <summary>
        /// Phone.
        /// </summary>
        [DatabaseField]
        public string Phone
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Phone"), "");
            }
            set
            {
                SetValue("Phone", value);
            }
        }


        /// <summary>
        /// Serving Countries.
        /// </summary>
        [DatabaseField]
        public string ServingCountries
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ServingCountries"), "");
            }
            set
            {
                SetValue("ServingCountries", value);
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Constructor.
        /// </summary>
        public SalesOffice()
            : base(CLASS_NAME)
        {
        }

        #endregion
    }
}
